# OUR PROBLEM FORMULATION

Our input is a tabular dataset showing the ratings of certain products given other features known for a product on Wish.com such as the merchant name, merchant id , color of the products and its sizes ..etc . Ratings are in categories from 1 to 5. The dataset is super big, unclean and it needs alot of work and preprocessing, and in order to make predictions we will use some machine learning models such as decision tree, support vector machine and naive bayes. the output needs to be the prediction of the rating of a new product from 1 to 5 without actually putting the product on the site plus it will help to understand under what certain conditions a product will get a high rate and most customers perfrences.

data mining has 4 basic functions,(Prediction function) which is The process of finding patterns from data using several variables to predict other variables of unknown type or value. (description function) which is known as The process of finding an important characteristic of data in a database. (Classification function),this is a process to find a model or function to describe the class of a data. Association functions (association)and this process is used to find a relationship that is contained in the attribute value of a data set.,

In data mining we may face some obstacles and challenges those challenges are all about developing a successful solution to our problem , the hardest of them in my opinion are complex data,datasets can include complex data elements ,another thing is that we have to make sure that our algorithm must be efficient and scalable to extract information from the big data and we should have enough knowledge and experience in order to use them if we needed to improve our algorithms.

what is the impact? real life impact

Noise and exceptional data must also be managed perfectly in data mining systems.and how we manage those noises will have a great impact on the performance of our algorithm and it can highly increase or decrease its accuracy, an ideal solution in my opinion will be measured in terms of metrics and performances

# Why Data Mining is a misnomer? What is another preferred name?

It is a misnomer because the goal is the extraction of patterns and knowledge from big data, not the extraction of the data itself, another name for data mining is knowledge discovery in data (KDD).

# What is the general knowledge discovery process? What is the difference between a data engineer and data scientist/AI engineer?

Knowledge discovery is the process of extracting the information from data that can be useful to your work or specialization.

Data engineers are responsible for forming and keeping the infrastructure and data architecture that support an organization’s IT systems. they need to have skills in programming, data storage, dbms, while Data scientists and AI engineers are people who analyze large amounts of data using statistical methods, especially AI and ML. Modern companies nowadays need data scientists to help them determine which ads to show customers for example.

# In data mining, what is the difference between prediction and categorization?

Classification is about discovering a model that defines the data classes and concepts. The idea is to use this model to predict the class. The derived model is dependent on the examination of sets of training data.

Categorization is the exercise of creating meaningful categories for a particular variable/feature in the dataset, for better inference/understanding.Once we have few but meaningful categories, it becomes easier to do data analysis.

#  Why data science/machine learning is a bad idea in the context of information security?

As a example,we can easily get the trainng samples from the model itself, and we can also know if there was a specific photo included in the data that we fitted.
When designing machine learning, security wasn't in mind. when most data learning models depend on static assumptions of the universe or world, security field is dynamic with never ending race between system designers and attackers and any soution for security domain needs to evolve over time in face of threats.


# What is CIA principle and how can we use it to access the security/privacy aspect of the AI system/pipelines?

The CIA triad is a guide for measurements in information security. Information security influences how information technology is used. it has 3 significant factors which are: Confidentiality which is  the protection of data from any unauthorized access, Integrity which its goal is to keep information accurate and consistent unless authorized changes are made ,Availability where information is available when it is needed.

When it comes to merging AI systems and security aspects, we'll be able to:

1- Discover threats and planned attacks

2- Neutrale cyber attacks which come in mails

3- predict social unrest in a region

CIA is Used in AI to Collect Social Media Data as Human behavior is data and AI is a data model

“What is new is the volume and velocity of collecting social media data,” said Joseph Gartin, head of the CIA’s Kent School.

# What is the experimental protocol used and how was it carried out? What preprocessing steps are used?

1- importing useful libraries is what i started with in order to deal with my data and be able to create my models

2- I read both of my training and testing data and dropped the id column from my training data

3- I wanted to view some features' unique values names and its counts in order to know if its somehow affecting the predictions annd to check if I'm gonna drop some of them

4- I dropped the unnecessary columns 

5- I applied label encoding on both my datasets

6- I splitted my data into features and target variables

7- I splitted the training data into 80% Train , 20% Validation to check my performance

8- I started applying my machine learning algorithms :
    
   - I fitted the model
   - viewed my predictions before tuning
   - tuned my hyperparameters
   - fitted my model again with the new parameters
   - printed my predictions performances (with my validation input) using confusion matrix,f1-score and classification report
   - and finally predicted my results using the testing set as an input
    
9- At some point I needed to scale my data (before using the SVM model) in order to give me better results



# Coding

In [1]:
#at first I needed to import some important libraries 
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, chi2

In [2]:
#then I read my data
df = pd.read_csv (r'train_new.csv') #training set 
dft = pd.read_csv (r'test_new.csv')#testing set
df = df.drop(['id'],axis=1) #I don't need the id column in training so I'll just drop it


In [3]:
#I wanted to view the 'merchant_profile_picture' unique values names and its counts in order to know if its somehow affecting the predictions
df.loc[:,'merchant_profile_picture'].unique()
df.loc[:,'merchant_profile_picture'].value_counts()
#looks like I'm not gonna drop it I will just label encode it later

https://s3-us-west-1.amazonaws.com/sweeper-production-merchantimage/dp_5acaf29d5ebcfd72403106a8.jpg    8
https://s3-us-west-1.amazonaws.com/sweeper-production-merchantimage/dp_55c8a4c33a698c6010edcd9e.jpg    6
https://s3-us-west-1.amazonaws.com/sweeper-production-merchantimage/dp_5533c83986ff95173dc017d0.jpg    6
https://s3-us-west-1.amazonaws.com/sweeper-production-merchantimage/dp_58ad449708de0c6dc59d9e06.jpg    5
https://s3-us-west-1.amazonaws.com/sweeper-production-merchantimage/dp_577fb2b368116418674befd9.jpg    4
                                                                                                      ..
https://s3-us-west-1.amazonaws.com/sweeper-production-merchantimage/dp_5756d060b833235cbc250227.jpg    1
https://s3-us-west-1.amazonaws.com/sweeper-production-merchantimage/dp_5541ba455252290c0b225b1f.jpg    1
https://s3-us-west-1.amazonaws.com/sweeper-production-merchantimage/dp_565537c7a9a8a4572be0bef5.jpg    1
https://s3-us-west-1.amazonaws.com/sweeper-production-m

In [4]:
#doing the same for 'merchant_id'
df.loc[:,'merchant_id'].unique()
df.loc[:,'merchant_id'].value_counts()
#also not gonna drop it 

5acaf29d5ebcfd72403106a8    8
558c2cdc89d53c4005ea2920    7
5533c83986ff95173dc017d0    6
583138b06339b410ab9663ec    6
582833faea77701b456c786a    6
                           ..
5ae5c3cb4215954239aff8b9    1
5864767762a1e84ca30df7c9    1
587f55e57f83404d58fe59fb    1
5ba0fe4673d934503a6cb6ad    1
5b6ec2f2838d931d2fbf7a28    1
Name: merchant_id, Length: 747, dtype: int64

In [5]:
df.loc[:,'merchant_rating_count'].unique()
df.loc[:,'merchant_rating_count'].value_counts()
#not gonna be dropped 

12309    8
32168    7
88193    6
55670    6
80093    6
        ..
2946     1
2055     1
23609    1
36       1
6632     1
Name: merchant_rating_count, Length: 718, dtype: int64

In [6]:
df.loc[:,'units_sold'].unique()
df.loc[:,'units_sold'].value_counts()
#not gonna be dropped

100       353
1000      280
5000      139
10000     125
20000      79
50         54
10         37
50000      12
100000      5
8           4
1           3
2           2
7           1
Name: units_sold, dtype: int64

In [7]:
df.loc[:,'units_sold'].unique()
df.loc[:,'units_sold'].value_counts()
#not gonna be dropped

100       353
1000      280
5000      139
10000     125
20000      79
50         54
10         37
50000      12
100000      5
8           4
1           3
2           2
7           1
Name: units_sold, dtype: int64

In [8]:
df.loc[:,'merchant_info_subtitle'].unique()
df.loc[:,'merchant_info_subtitle'].value_counts()
#same as the others

86 % avis positifs (12,309 notes)    8
83 % avis positifs (32,168 notes)    7
85 % avis positifs (80,093 notes)    5
84 % avis positifs (1,047 notes)     5
85 % avis positifs (5,264 notes)     5
                                    ..
90 % avis positifs (2,359 notes)     1
90 % avis positifs (26,833 notes)    1
86 % avis positifs (4,335 notes)     1
79 % avis positifs (667 notes)       1
78 % avis positifs (6,632 notes)     1
Name: merchant_info_subtitle, Length: 808, dtype: int64

In [9]:
df.loc[:,'merchant_title'].unique()
df.loc[:,'merchant_title'].value_counts()
#not gonna drop it

Suyi Technology                             8
guangzhouweishiweifushiyouxiangongsi        7
shuilingjiao international trade company    6
sjhdstoer                                   6
Sangboo Store                               6
                                           ..
Wwenliping                                  1
yourvogue                                   1
caohongbo                                   1
bumanke003                                  1
OIUG 56465                                  1
Name: merchant_title, Length: 747, dtype: int64

In [10]:
df.loc[:,'merchant_has_profile_picture'].unique()
df.loc[:,'merchant_has_profile_picture'].value_counts()
#alot of zeros and small amount of ones when compared with zeros so I will just drop the column

0    924
1    170
Name: merchant_has_profile_picture, dtype: int64

In [11]:
df.loc[:,'has_urgency_banner'].unique()
df.loc[:,'has_urgency_banner'].value_counts()
#lots of missing data! will be dropped

1.0    349
Name: has_urgency_banner, dtype: int64

In [12]:
df.loc[:,'merchant_name'].unique()
df.loc[:,'merchant_name'].value_counts()
# okay it has lots of unique values but to be honest ..Logically I don't feel like the name of the merchant 
#will affect how I will rate a product cause if he is the most famous merchant or brand name in the world and I still didn't like the
#quality of what I purchased I will still give it a small rating no matter what so I will drop this column

greatexpectationstechnology    8
广州唯适唯服饰有限公司                    7
smarthomeinternationalcoltd    6
fengjinying                    6
sangboostore                   6
                              ..
wwenliping                     1
yourvogue                      1
caohongbo                      1
bumanke003                     1
oiug56465                      1
Name: merchant_name, Length: 746, dtype: int64

In [13]:
df.loc[:,'urgency_text'].unique()
df.loc[:,'urgency_text'].value_counts()
#so many missing data so I will drop the column

Quantité limitée !                  348
Réduction sur les achats en gros      1
Name: urgency_text, dtype: int64

In [14]:
df.loc[:,'rating_count'].unique()
df.loc[:,'rating_count'].value_counts()
#I also feel like the rating of others won't affect mine If my experience wasn't the best with a certain product product
#so I will drop this

0       30
2       27
4       22
6       17
10      15
        ..
1183     1
370      1
569      1
4421     1
135      1
Name: rating_count, Length: 584, dtype: int64

In [15]:
df.loc[:,'shipping_option_name'].unique()
df.loc[:,'shipping_option_name'].value_counts()
#1047 out of 1094 contains the Livraison standard ! I'll drop this column for sure it will have no huge effect on my predictions

Livraison standard         1047
Standard Shipping            16
Envio Padrão                  6
الشحن القياسي                 4
Expediere Standard            4
Envío normal                  3
Standardversand               3
Livraison Express             3
Standardowa wysyłka           2
Standart Gönderi              2
Стандартная доставка          2
Spedizione standard           1
ការដឹកជញ្ជូនតាមស្តង់ដារ       1
Name: shipping_option_name, dtype: int64

In [16]:
df

price  retail_price currency_buyer  units_sold  uses_ad_boosts  rating  \
0      8.00             7            EUR       10000               1     4.0   
1      8.00             7            EUR        1000               0     4.0   
2      6.00            34            EUR         100               0     4.0   
3      4.67             4            EUR         100               1     3.0   
4      8.00            11            EUR        1000               0     4.0   
...     ...           ...            ...         ...             ...     ...   
1089   4.00             4            EUR       10000               0     4.0   
1090   5.00             5            EUR        1000               0     5.0   
1091   9.00            48            EUR        1000               1     4.0   
1092  11.00            10            EUR       10000               1     4.0   
1093   7.00             6            EUR        1000               1     3.0   

      rating_count  badges_count  badge_local_product  badge_product_quality  \
0             1670             0                    0                      0   
1              843             1                    1                      0   
2               10             0                    0                      0   
3               82             0                    0                      0   
4              127             0                    0                      0   
...            ...           ...                  ...                    ...   
1089          2150             0                    0                      0   
1090           377             1                    0                      1   
1091           135             0                    0                      0   
1092          1479             0                    0                      0   
1093           141             0                    0                      0   

      ...                         merchant_title                merchant_name  \
0     ...                             keepahorse                   keepahorse   
1     ...  shanghaimingqidianqikejiyouxiangongsi                 上海铭启电气科技有限公司   
2     ...                            zhaodongmei                  zhaodongmei   
3     ...                             pookie0331                   pookie0331   
4     ...                      shitongyi12683626            shitongyi12683626   
...   ...                                    ...                          ...   
1089  ...                         fantastic_tune               fantastic_tune   
1090  ...                                zzbllss                      zzbllss   
1091  ...                             OIUG 56465                    oiug56465   
1092  ...                             yubenqiang                   yubenqiang   
1093  ...                        Suyi Technology  greatexpectationstechnology   

                  merchant_info_subtitle merchant_rating_count  \
0      88 % avis positifs (66,644 notes)                 66644   
1      91 % avis positifs (25,752 notes)                 25752   
2       83 % avis positifs (3,897 notes)                  3897   
3       87 % avis positifs (7,497 notes)                  7497   
4         91 % avis positifs (173 notes)                   173   
...                                  ...                   ...   
1089  92 % avis positifs (230,951 notes)                230951   
1090                       (2,904 notes)                  2904   
1091    78 % avis positifs (6,632 notes)                  6632   
1092    83 % avis positifs (5,816 notes)                  5816   
1093   86 % avis positifs (12,309 notes)                 12309   

      merchant_rating               merchant_id  merchant_has_profile_picture  \
0            4.137582  577fb2b368116418674befd9                             1   
1            4.256873  566a3ef17233ff2686443082                             0   
2            3.928920  5aacd6c1ccf0c83e5a6f3de0                            

In [17]:
#dropping unnecessary columns
df=df.drop(['merchant_has_profile_picture','has_urgency_banner','merchant_name','urgency_text','rating_count','shipping_option_name'],axis=1)
dft=dft.drop(['merchant_has_profile_picture','has_urgency_banner','merchant_name','urgency_text','rating_count','shipping_option_name'],axis=1)
df #viewing my training set after dropping them

price  retail_price currency_buyer  units_sold  uses_ad_boosts  rating  \
0      8.00             7            EUR       10000               1     4.0   
1      8.00             7            EUR        1000               0     4.0   
2      6.00            34            EUR         100               0     4.0   
3      4.67             4            EUR         100               1     3.0   
4      8.00            11            EUR        1000               0     4.0   
...     ...           ...            ...         ...             ...     ...   
1089   4.00             4            EUR       10000               0     4.0   
1090   5.00             5            EUR        1000               0     5.0   
1091   9.00            48            EUR        1000               1     4.0   
1092  11.00            10            EUR       10000               1     4.0   
1093   7.00             6            EUR        1000               1     3.0   

      badges_count  badge_local_product  badge_product_quality  \
0                0                    0                      0   
1                1                    1                      0   
2                0                    0                      0   
3                0                    0                      0   
4                0                    0                      0   
...            ...                  ...                    ...   
1089             0                    0                      0   
1090             1                    0                      1   
1091             0                    0                      0   
1092             0                    0                      0   
1093             0                    0                      0   

      badge_fast_shipping  ... inventory_total origin_country  \
0                       0  ...              50             CN   
1                       0  ...              50             CN   
2                       0  ...              50             CN   
3                       0  ...              50             CN   
4                       0  ...              50             CN   
...                   ...  ...             ...            ...   
1089                    0  ...              50             CN   
1090                    0  ...              50             CN   
1091                    0  ...              50             CN   
1092                    0  ...              50             CN   
1093                    0  ...              50             CN   

                             merchant_title  \
0                                keepahorse   
1     shanghaimingqidianqikejiyouxiangongsi   
2                               zhaodongmei   
3                                pookie0331   
4                         shitongyi12683626   
...                                     ...   
1089                         fantastic_tune   
1090                                zzbllss   
1091                             OIUG 56465   
1092                             yubenqiang   
1093                        Suyi Technology   

                  merchant_info_subtitle  merchant_rating_count  \
0      88 % avis positifs (66,644 notes)                  66644   
1      91 % avis positifs (25,752 notes)                  25752   
2       83 % avis positifs (3,897 notes)                   3897   
3       87 % avis positifs (7,497 notes)                   7497   
4         91 % avis positifs (173 notes)                    173   
...                                  ...                    ...   
1089  92 % avis positifs (230,951 notes)                 230951   
1090                       (2,904 notes)                   2904   
1091    78 % avis positifs (6,632 notes)                   6632   
1092    83 % avis positifs (5,816 notes)                   5816   
1093   86 % avis positifs (12,309 notes)                  12309   

      merchant_rating               merchant_id  \
0            4.137582  577fb2b368116418674befd9   

In [18]:
dft

price  retail_price currency_buyer  units_sold  uses_ad_boosts  \
0     5.75             5            EUR          10               1   
1     7.00             7            EUR        5000               0   
2     5.00            16            EUR        1000               1   
3    18.00            27            EUR        5000               1   
4    12.00            81            EUR       20000               0   
..     ...           ...            ...         ...             ...   
474  16.00            14            EUR         100               1   
475   6.00            17            EUR        5000               1   
476   4.83            51            EUR          50               1   
477   3.00             3            EUR         100               1   
478  13.00            11            EUR         100               1   

     badges_count  badge_local_product  badge_product_quality  \
0               0                    0                      0   
1               0                    0                      0   
2               0                    0                      0   
3               0                    0                      0   
4               0                    0                      0   
..            ...                  ...                    ...   
474             0                    0                      0   
475             0                    0                      0   
476             0                    0                      0   
477             0                    0                      0   
478             0                    0                      0   

     badge_fast_shipping                                               tags  \
0                      0  Funny,letter print,Fashion,Shirt,Sleeve,Summer...   
1                      0  Women Vest,Vest,Fashion,Women Blouse,long dres...   
2                      0  hollowouttanktop,Tanktops for women,Plus Size,...   
3                      0  men jeans,Shorts,Summer,Vintage,Denim,Men,casu...   
4                      0  Shorts,Lace,pants,Dress,Women Leggings,Hot pan...   
..                   ...                                                ...   
474                    0  mensummertshirt,Summer,Fashion,Men's Fashion,S...   
475                    0  blouse,Summer,Vest,Plus Size,letter print,cute...   
476                    0  blouse,Summer,Plus Size,Tops & Blouses,Shirt,W...   
477                    0  Summer,slideslipper,Sandals,fur,Indoor,Fox,Ind...   
478                    0  Summer,Plus Size,2pieceset,Women,slim,T Shirts...   

     ... origin_country      merchant_title  \
0    ...             CN           liyang163   
1    ...             CN  singing  the  song   
2    ...             CN     Surper boutique   
3    ...             CN            postonny   
4    ...             CN     fashionforgirls   
..   ...            ...                 ...   
474  ...             VE        HERNADEZYELI   
475  ...             CN         First Crush   
476  ...             VE           saulstore   
477  ...             CN            lkwelyly   
478  ...             CN                rtgh   

                   merchant_info_subtitle  merchant_rating_count  \
0            33 % avis positifs (3 notes)                      3   
1        86 % avis positifs (4,213 notes)                   4213   
2       85 % avis positifs (10,501 notes)                  10501   
3       86 % avis positifs (15,855 notes)                  15855   
4      88 % avis positifs (151,914 notes)                 151914   
..                                    ...                    ...   
474        70 % avis positifs (572 notes)                    572   
475     87 % avis positifs (50,864 notes)                  50864   
476         85 % avis positifs (57 notes)                     57   
477      87 % avis positifs (1,086 notes)                   1086   
478  86% Feedback pozitiv (45,151 rating)                  45151   

     merchant_rating               merch

In [19]:
# I noticed that my data set has alot of categorical values 
#lots of machine learning algorithms won't be able to accept them so I'll need to turn them into numerical values
#to be honest I tried the hot encoding but I had a problem when I applied it seperatly on training set and testing set 
#as it gave me different number of columns for each set which is a super huge problem
#instead I decided to apply the label encoding and it worked very well!
#the following code is when I used the LabelEncoder to Encode Multiple Columns All at Once for both trainig and testing

#for training
from sklearn.preprocessing import LabelEncoder

cols = ["currency_buyer","tags","product_color","product_variation_size_id","merchant_title","merchant_info_subtitle","merchant_id","merchant_profile_picture","origin_country","theme","crawl_month"]

# Encode labels of multiple columns at once

df[cols] = df[cols].apply(LabelEncoder().fit_transform)

df


price  retail_price  currency_buyer  units_sold  uses_ad_boosts  rating  \
0      8.00             7               0       10000               1     4.0   
1      8.00             7               0        1000               0     4.0   
2      6.00            34               0         100               0     4.0   
3      4.67             4               0         100               1     3.0   
4      8.00            11               0        1000               0     4.0   
...     ...           ...             ...         ...             ...     ...   
1089   4.00             4               0       10000               0     4.0   
1090   5.00             5               0        1000               0     5.0   
1091   9.00            48               0        1000               1     4.0   
1092  11.00            10               0       10000               1     4.0   
1093   7.00             6               0        1000               1     3.0   

      badges_count  badge_local_product  badge_product_quality  \
0                0                    0                      0   
1                1                    1                      0   
2                0                    0                      0   
3                0                    0                      0   
4                0                    0                      0   
...            ...                  ...                    ...   
1089             0                    0                      0   
1090             1                    0                      1   
1091             0                    0                      0   
1092             0                    0                      0   
1093             0                    0                      0   

      badge_fast_shipping  ...  inventory_total  origin_country  \
0                       0  ...               50               0   
1                       0  ...               50               0   
2                       0  ...               50               0   
3                       0  ...               50               0   
4                       0  ...               50               0   
...                   ...  ...              ...             ...   
1089                    0  ...               50               0   
1090                    0  ...               50               0   
1091                    0  ...               50               0   
1092                    0  ...               50               0   
1093                    0  ...               50               0   

      merchant_title  merchant_info_subtitle  merchant_rating_count  \
0                472                     617                  66644   
1                584                     734                  25752   
2                725                     332                   3897   
3                556                     555                   7497   
4                597                     726                    173   
...              ...                     ...                    ...   
1089             399                     767                 230951   
1090             746                      61                   2904   
1091             187                     213                   6632   
1092             708                     339                   5816   
1093             255                     462                  12309   

      merchant_rating  merchant_id  merchant_profile_picture  theme  \
0            4.137582          201                        67      0   
1            4.256873          132                       100      0   
2            3.928920          498                       100      0   
3            4.079365          272                       100      0   
4            4.306358          614                       100      0   
...               ...          ...                       ...    ...   
1089         4.311066           24                       100      0   
1090         4

In [20]:
#for testing
cols = ["currency_buyer","tags","product_color","product_variation_size_id","merchant_title","merchant_info_subtitle","merchant_id","merchant_profile_picture","origin_country","theme","crawl_month"]

# Encode labels of multiple columns at once

dft[cols] = dft[cols].apply(LabelEncoder().fit_transform)

dft

price  retail_price  currency_buyer  units_sold  uses_ad_boosts  \
0     5.75             5               0          10               1   
1     7.00             7               0        5000               0   
2     5.00            16               0        1000               1   
3    18.00            27               0        5000               1   
4    12.00            81               0       20000               0   
..     ...           ...             ...         ...             ...   
474  16.00            14               0         100               1   
475   6.00            17               0        5000               1   
476   4.83            51               0          50               1   
477   3.00             3               0         100               1   
478  13.00            11               0         100               1   

     badges_count  badge_local_product  badge_product_quality  \
0               0                    0                      0   
1               0                    0                      0   
2               0                    0                      0   
3               0                    0                      0   
4               0                    0                      0   
..            ...                  ...                    ...   
474             0                    0                      0   
475             0                    0                      0   
476             0                    0                      0   
477             0                    0                      0   
478             0                    0                      0   

     badge_fast_shipping  tags  ...  origin_country  merchant_title  \
0                      0    26  ...               1             250   
1                      0   303  ...               1             321   
2                      0   396  ...               1             114   
3                      0   401  ...               1             286   
4                      0    66  ...               1             187   
..                   ...   ...  ...             ...             ...   
474                    0   402  ...               3              48   
475                    0   365  ...               1              41   
476                    0   357  ...               3             307   
477                    0   276  ...               1             252   
478                    0   122  ...               1             305   

     merchant_info_subtitle  merchant_rating_count  merchant_rating  \
0                        80                      3         2.333333   
1                       261                   4213         4.058391   
2                       206                  10501         4.029235   
3                       249                  15855         4.052917   
4                       314                 151914         4.127921   
..                      ...                    ...              ...   
474                      82                    572         3.367133   
475                     298                  50864         4.079644   
476                     232                     57         3.824561   
477                     274                   1086         4.056169   
478                     272                  45151         4.032956   

     merchant_id  merchant_profile_picture  theme  crawl_month    id  
0            380                        49      0            0   937  
1            163                        49      0            0   270  
2             94                        49      0            0   308  
3            255                        49      0            0   913  
4              7                        49      0            0   403  
..           ...                       ...    ...          ...   ...  
474          359                        49      0            0  1166  
475          193                        38      0            0  1416  
476          3

In [21]:
#Splitting the data into features and target variables
xtr=df.loc[:, df.columns != 'rating'] #here I started splitting my training set (df) into x (input)
ytr=df.rating #and y the output (my target) which tells the rating from 1 to 5
xts=dft.drop(['id'],axis=1) #on my testing data, I don't wanna consider the id column as a feature so i dropped it
idts=dft['id'] #and here i put the dropped id column in another variable cause I will need in the end to call the product with its id while testing
xts #just vieweing my testing dataset

price  retail_price  currency_buyer  units_sold  uses_ad_boosts  \
0     5.75             5               0          10               1   
1     7.00             7               0        5000               0   
2     5.00            16               0        1000               1   
3    18.00            27               0        5000               1   
4    12.00            81               0       20000               0   
..     ...           ...             ...         ...             ...   
474  16.00            14               0         100               1   
475   6.00            17               0        5000               1   
476   4.83            51               0          50               1   
477   3.00             3               0         100               1   
478  13.00            11               0         100               1   

     badges_count  badge_local_product  badge_product_quality  \
0               0                    0                      0   
1               0                    0                      0   
2               0                    0                      0   
3               0                    0                      0   
4               0                    0                      0   
..            ...                  ...                    ...   
474             0                    0                      0   
475             0                    0                      0   
476             0                    0                      0   
477             0                    0                      0   
478             0                    0                      0   

     badge_fast_shipping  tags  ...  inventory_total  origin_country  \
0                      0    26  ...               50               1   
1                      0   303  ...               50               1   
2                      0   396  ...               50               1   
3                      0   401  ...               50               1   
4                      0    66  ...               50               1   
..                   ...   ...  ...              ...             ...   
474                    0   402  ...               50               3   
475                    0   365  ...               50               1   
476                    0   357  ...               50               3   
477                    0   276  ...               50               1   
478                    0   122  ...               50               1   

     merchant_title  merchant_info_subtitle  merchant_rating_count  \
0               250                      80                      3   
1               321                     261                   4213   
2               114                     206                  10501   
3               286                     249                  15855   
4               187                     314                 151914   
..              ...                     ...                    ...   
474              48                      82                    572   
475              41                     298                  50864   
476             307                     232                     57   
477             252                     274                   1086   
478             305                     272                  45151   

     merchant_rating  merchant_id  merchant_profile_picture  theme  \
0           2.333333          380                        49      0   
1           4.058391          163                        49      0   
2           4.029235           94                        49      0   
3           4.052917          255                        49      0   
4           4.127921            7                        49      0   
..               ...          ...                       ...    ...   
474         3.367133          359                        49      0   
475         4.079644          193                        38      0   
476         3.824561   

In [22]:
xtr

price  retail_price  currency_buyer  units_sold  uses_ad_boosts  \
0      8.00             7               0       10000               1   
1      8.00             7               0        1000               0   
2      6.00            34               0         100               0   
3      4.67             4               0         100               1   
4      8.00            11               0        1000               0   
...     ...           ...             ...         ...             ...   
1089   4.00             4               0       10000               0   
1090   5.00             5               0        1000               0   
1091   9.00            48               0        1000               1   
1092  11.00            10               0       10000               1   
1093   7.00             6               0        1000               1   

      badges_count  badge_local_product  badge_product_quality  \
0                0                    0                      0   
1                1                    1                      0   
2                0                    0                      0   
3                0                    0                      0   
4                0                    0                      0   
...            ...                  ...                    ...   
1089             0                    0                      0   
1090             1                    0                      1   
1091             0                    0                      0   
1092             0                    0                      0   
1093             0                    0                      0   

      badge_fast_shipping  tags  ...  inventory_total  origin_country  \
0                       0   562  ...               50               0   
1                       0   650  ...               50               0   
2                       0   493  ...               50               0   
3                       0   410  ...               50               0   
4                       0   225  ...               50               0   
...                   ...   ...  ...              ...             ...   
1089                    0   768  ...               50               0   
1090                    0     9  ...               50               0   
1091                    0   458  ...               50               0   
1092                    0   371  ...               50               0   
1093                    0   838  ...               50               0   

      merchant_title  merchant_info_subtitle  merchant_rating_count  \
0                472                     617                  66644   
1                584                     734                  25752   
2                725                     332                   3897   
3                556                     555                   7497   
4                597                     726                    173   
...              ...                     ...                    ...   
1089             399                     767                 230951   
1090             746                      61                   2904   
1091             187                     213                   6632   
1092             708                     339                   5816   
1093             255                     462                  12309   

      merchant_rating  merchant_id  merchant_profile_picture  theme  \
0            4.137582          201                        67      0   
1            4.256873          132                       100      0   
2            3.928920          498                       100      0   
3            4.079365          272                       100      0   
4            4.306358          614                       100      0   
...               ...          ...                       ...    ...   
1089         4.311066           24                       100      0   
1090         4.422521          400    

In [23]:
#Splitting training data into 80% Train , 20% Validation
from sklearn.model_selection import train_test_split
xtr_train, xtr_valid, ytr_train, ytr_valid = train_test_split(xtr, ytr, test_size = 0.2, random_state=3)
xtr_train

price  retail_price  currency_buyer  units_sold  uses_ad_boosts  \
960    4.66             5               0       10000               0   
103    5.66             5               0       20000               0   
357    4.00             4               0          50               1   
422   11.00           168               0          10               0   
925    8.00             9               0         100               1   
...     ...           ...             ...         ...             ...   
1021  11.00            20               0         100               0   
789    2.72            17               0        1000               1   
256    5.77             9               0         100               0   
968   24.00            59               0        1000               1   
952    3.65             9               0         100               1   

      badges_count  badge_local_product  badge_product_quality  \
960              1                    0                      1   
103              0                    0                      0   
357              0                    0                      0   
422              0                    0                      0   
925              0                    0                      0   
...            ...                  ...                    ...   
1021             0                    0                      0   
789              0                    0                      0   
256              0                    0                      0   
968              0                    0                      0   
952              2                    1                      0   

      badge_fast_shipping  tags  ...  inventory_total  origin_country  \
960                     0   635  ...               50               0   
103                     0   720  ...               50               0   
357                     0   270  ...               50               0   
422                     0   392  ...               50               0   
925                     0   404  ...               50               0   
...                   ...   ...  ...              ...             ...   
1021                    0   477  ...               50               0   
789                     0   182  ...               50               0   
256                     0   260  ...               50               0   
968                     0   597  ...               50               0   
952                     1   298  ...               50               0   

      merchant_title  merchant_info_subtitle  merchant_rating_count  \
960              107                     786                  85562   
103              484                     716                   8205   
357              475                     205                    254   
422              649                     437                     47   
925              179                       8                   1585   
...              ...                     ...                    ...   
1021             370                     649                   3120   
789              612                     653                  37375   
256              386                     472                   2044   
968              573                     701                   4084   
952              502                     751                   8888   

      merchant_rating  merchant_id  merchant_profile_picture  theme  \
960          4.394591          330                       100      0   
103          4.195856          372                       100      0   
357          3.515748          661                       100      0   
422          3.914894          726                       100      0   
925          4.076972          506                       100      0   
...               ...          ...                       ...    ...   
1021         4.174679          550                       100      0   
789          4.179425          195    

In [24]:
ytr_train

960     5.0
103     4.0
357     1.0
422     3.0
925     4.0
       ... 
1021    4.0
789     4.0
256     3.0
968     5.0
952     3.0
Name: rating, Length: 875, dtype: float64

In [25]:
#let's start applying our machine learning algorothim and I wanted to begin with the decision tree model
from sklearn.tree import DecisionTreeClassifier
# I've created the decision tree classifier by passing the  random state paramter to DecisionTreeClassifier().
model = DecisionTreeClassifier(random_state=3)
#the training process by using the model.fit() method. (before tuning)
model.fit(xtr_train, ytr_train)
y_pred = model.predict(xtr_valid) 
y_pred #showing my predictions before tuning

array([4., 4., 4., 5., 4., 4., 3., 4., 5., 3., 5., 4., 5., 4., 3., 4., 4.,
       4., 5., 4., 4., 4., 1., 5., 4., 4., 4., 3., 4., 4., 4., 3., 4., 4.,
       4., 4., 3., 4., 4., 3., 3., 3., 4., 5., 4., 5., 4., 4., 4., 4., 4.,
       3., 4., 4., 4., 4., 4., 4., 3., 4., 4., 4., 4., 4., 4., 4., 4., 3.,
       5., 4., 4., 4., 3., 4., 4., 4., 5., 4., 4., 3., 5., 4., 5., 5., 4.,
       4., 4., 3., 3., 4., 4., 4., 5., 5., 4., 4., 4., 4., 4., 3., 4., 3.,
       4., 4., 5., 5., 5., 4., 3., 4., 3., 4., 4., 4., 3., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 5., 4., 3., 4., 4., 4., 5., 4., 4., 4., 4.,
       4., 4., 4., 3., 3., 4., 4., 4., 4., 4., 4., 4., 4., 4., 3., 4., 4.,
       4., 4., 5., 2., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 3., 3., 4.,
       5., 4., 4., 3., 5., 5., 4., 5., 4., 4., 3., 4., 4., 4., 5., 4., 5.,
       4., 4., 4., 4., 4., 4., 3., 4., 3., 4., 3., 4., 4., 4., 4., 3., 4.,
       4., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 3., 4., 4., 4.])

In [26]:
#Tuning the hyperparameters using randomizedSearchCV
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
# Setup the parameters and distributions to sample from: param_dist
param_dist = {"max_depth": [3, None],
              "max_features": randint(1, 9),
              "min_samples_leaf": randint(1, 9),
              "criterion": ["gini", "entropy"]}
# Instantiate the RandomizedSearchCV object: tree_cv
tree_cv = RandomizedSearchCV(model, param_dist, cv=5)
# Fit it to the data
tree_cv.fit(xtr_train,ytr_train)

C:\Users\mylap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=3),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [3, None],
                                        'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000002AE8540ECA0>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000002AE8541F0D0>})

In [27]:
#Validation after tuning
y_pred = tree_cv.predict(xtr_valid)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(ytr_valid, y_pred))
print(classification_report(ytr_valid, y_pred))

[[  0   0   0   0   1   0]
 [  0   0   0   3   0   0]
 [  0   0   4  28   0   0]
 [  0   0   4 148   0   0]
 [  0   0   1  24   5   0]
 [  0   0   0   1   0   0]]
              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00         1
         2.0       0.00      0.00      0.00         3
         3.0       0.44      0.12      0.20        32
         4.0       0.73      0.97      0.83       152
         5.0       0.83      0.17      0.28        30
         6.0       0.00      0.00      0.00         1

    accuracy                           0.72       219
   macro avg       0.33      0.21      0.22       219
weighted avg       0.68      0.72      0.64       219



C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [28]:
from sklearn.metrics import f1_score
f1_score(ytr_valid, y_pred, average='micro') 


0.7168949771689497

In [29]:
# concatenating x_test and id_test along columns in order to be able to call products with its ids when testing
final_test = pd.concat([xts,idts], axis=1)
final_test.set_index("id", inplace = True)

In [30]:
_id = final_test.index

In [31]:
#Testing Decision Tree

pred_test = tree_cv.predict(final_test) #storing our predictions is pred_test file

pred_df = pd.DataFrame(data={'id': np.asarray(_id), 'rating': pred_test})

pred_df.to_csv('pred_walkthrough.csv', index=False) #generating the submission file


In [32]:
#after submitting the pred_walkthrough file on kaggle , it gave me an accuracy of 0.74 
#I wanna improve it 

In [33]:
from sklearn import tree
model = tree.DecisionTreeClassifier(max_depth=3,random_state=42)
model

DecisionTreeClassifier(max_depth=3, random_state=42)

In [34]:
model.fit(xtr_train, ytr_train)
#tuning but this time using GriddearchCV
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
params = {
    'max_depth': [2, 3, 5, 10, 20],
    'min_samples_leaf': [5, 10, 20, 50, 100],
    'criterion': ["gini", "entropy"]
}

# Instantiate the grid search model
grid_search = GridSearchCV(estimator=model, 
                           param_grid=params, 
                           cv=4, n_jobs=-1, verbose=1, scoring = "accuracy")

In [36]:
grid_search.fit(xtr_train, ytr_train) #fitting the model
score_df = pd.DataFrame(grid_search.cv_results_)

Fitting 4 folds for each of 50 candidates, totalling 200 fits


C:\Users\mylap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=4.
  warnings.warn(("The least populated class in y has only %d"


In [37]:
#Validation after tuning
y_pred = grid_search.predict(xtr_valid)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(ytr_valid, y_pred))
print(classification_report(ytr_valid, y_pred))

[[  0   0   0   1   0   0]
 [  0   0   0   1   2   0]
 [  0   0   4  28   0   0]
 [  0   0   4 147   1   0]
 [  0   0   3  21   6   0]
 [  0   0   0   1   0   0]]
              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00         1
         2.0       0.00      0.00      0.00         3
         3.0       0.36      0.12      0.19        32
         4.0       0.74      0.97      0.84       152
         5.0       0.67      0.20      0.31        30
         6.0       0.00      0.00      0.00         1

    accuracy                           0.72       219
   macro avg       0.29      0.22      0.22       219
weighted avg       0.66      0.72      0.65       219



C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [38]:
pred_test = grid_search.predict(final_test)

pred_df = pd.DataFrame(data={'id': np.asarray(_id), 'rating': pred_test})

pred_df.to_csv('pred_walkthrough.csv', index=False)  #generating the new submission file

In [39]:
#after submitting the pred_walkthrough file on kaggle I noticed a huge increasment in accuracy, it became 0.78242
#I want to try a differnt model 
#I will go with Support vector machine

In [44]:
#I need to scale my data before applying the svm model, I will use MinMaxScaler()
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
xtr_train=pd.DataFrame(scaler.fit_transform(xtr_train),
            columns=xtr_train.columns, index=xtr_train.index) #scaling the train set
xtr_train #viewing it after scaling




price  retail_price  currency_buyer  units_sold  uses_ad_boosts  \
960   0.140769         0.012             0.0    0.099991             0.0   
103   0.179231         0.012             0.0    0.199992             0.0   
357   0.115385         0.008             0.0    0.000490             1.0   
422   0.384615         0.664             0.0    0.000090             0.0   
925   0.269231         0.028             0.0    0.000990             1.0   
...        ...           ...             ...         ...             ...   
1021  0.384615         0.072             0.0    0.000990             0.0   
789   0.066154         0.060             0.0    0.009990             1.0   
256   0.183462         0.028             0.0    0.000990             0.0   
968   0.884615         0.228             0.0    0.009990             1.0   
952   0.101923         0.028             0.0    0.000990             1.0   

      badges_count  badge_local_product  badge_product_quality  \
960       0.333333                  0.0                    1.0   
103       0.000000                  0.0                    0.0   
357       0.000000                  0.0                    0.0   
422       0.000000                  0.0                    0.0   
925       0.000000                  0.0                    0.0   
...            ...                  ...                    ...   
1021      0.000000                  0.0                    0.0   
789       0.000000                  0.0                    0.0   
256       0.000000                  0.0                    0.0   
968       0.000000                  0.0                    0.0   
952       0.666667                  1.0                    0.0   

      badge_fast_shipping      tags  ...  inventory_total  origin_country  \
960                   0.0  0.710291  ...              1.0             0.0   
103                   0.0  0.805369  ...              1.0             0.0   
357                   0.0  0.302013  ...              1.0             0.0   
422                   0.0  0.438479  ...              1.0             0.0   
925                   0.0  0.451902  ...              1.0             0.0   
...                   ...       ...  ...              ...             ...   
1021                  0.0  0.533557  ...              1.0             0.0   
789                   0.0  0.203579  ...              1.0             0.0   
256                   0.0  0.290828  ...              1.0             0.0   
968                   0.0  0.667785  ...              1.0             0.0   
952                   1.0  0.333333  ...              1.0             0.0   

      merchant_title  merchant_info_subtitle  merchant_rating_count  \
960         0.143432                0.973978               0.039341   
103         0.648794                0.887237               0.003771   
357         0.636729                0.254027               0.000115   
422         0.869973                0.541512               0.000020   
925         0.239946                0.009913               0.000727   
...              ...                     ...                    ...   
1021        0.495979                0.804213               0.001433   
789         0.820375                0.809170               0.017184   
256         0.517426                0.584882               0.000938   
968         0.768097                0.868649               0.001876   
952         0.672922                0.930607               0.004085   

      merchant_rating  merchant_id  merchant_profile_picture  theme  \
960          0.919481     0.442953                       1.0    0.0   
103          0.793755     0.499329                       1.0    0.0   
357          0.363494     0.887248                       1.0    0.0   
422          0.616008     0.974497                       1.0    0.0   
925          0.718544     0.679195                       1.0    0.0   
...               ...          ...                       ...    ...   
1021         0.780358     0.

In [45]:
xtr_valid=pd.DataFrame(scaler.fit_transform(xtr_valid),
            columns=xtr_valid.columns, index=xtr_valid.index) #scaling the valid set
xtr_valid #viewing it after scaling

price  retail_price  currency_buyer  units_sold  uses_ad_boosts  \
446   0.155049         0.124             0.0    0.049905             0.0   
469   0.133925         0.020             0.0    0.000900             0.0   
362   0.091677         0.016             0.0    0.099910             1.0   
900   0.302915         0.048             0.0    0.199920             0.0   
391   0.028306         0.004             0.0    0.000400             0.0   
...        ...           ...             ...         ...             ...   
706   0.112801         0.096             0.0    0.049905             0.0   
636   0.007182         0.032             0.0    0.000900             0.0   
1089  0.049430         0.008             0.0    0.099910             0.0   
92    0.239544         0.036             0.0    0.000900             1.0   
612   0.133925         0.080             0.0    0.199920             1.0   

      badges_count  badge_local_product  badge_product_quality  \
446            0.0                  0.0                    0.0   
469            0.0                  0.0                    0.0   
362            0.0                  0.0                    0.0   
900            1.0                  0.0                    1.0   
391            0.0                  0.0                    0.0   
...            ...                  ...                    ...   
706            0.0                  0.0                    0.0   
636            0.0                  0.0                    0.0   
1089           0.0                  0.0                    0.0   
92             0.0                  0.0                    0.0   
612            0.0                  0.0                    0.0   

      badge_fast_shipping      tags  ...  inventory_total  origin_country  \
446                   0.0  0.697413  ...              1.0             0.0   
469                   0.0  0.862767  ...              1.0             0.0   
362                   0.0  0.354331  ...              1.0             0.0   
900                   0.0  0.643420  ...              1.0             0.0   
391                   0.0  0.130484  ...              1.0             0.0   
...                   ...       ...  ...              ...             ...   
706                   0.0  0.773903  ...              1.0             0.0   
636                   0.0  0.185602  ...              1.0             0.0   
1089                  0.0  0.859393  ...              1.0             0.0   
92                    0.0  0.275591  ...              1.0             0.0   
612                   0.0  0.103487  ...              1.0             0.0   

      merchant_title  merchant_info_subtitle  merchant_rating_count  \
446         0.300539                0.788030               0.166432   
469         0.842318                0.809227               0.000421   
362         0.482480                0.184539               0.008701   
900         0.260108                0.985037               0.022508   
391         0.560647                0.317955               0.000026   
...              ...                     ...                    ...   
706         0.210243                0.154613               0.006582   
636         0.752022                0.557357               0.009786   
1089        0.536388                0.952618               0.274975   
92          0.769542                0.640898               0.053752   
612         0.303235                0.402743               0.021129   

      merchant_rating  merchant_id  merchant_profile_picture  theme  \
446          0.704622     0.034993                  1.000000    0.0   
469          0.750650     0.497981                  1.000000    0.0   
362          0.540545     0.332436                  1.000000    0.0   
900          0.863378     0.009421                  0.010309    0.0   
391          0.610625     0.934051                  1.000000    0.0   
...               ...          ...                       ...    ...   
706          0.584828     0.

In [46]:
xts=pd.DataFrame(scaler.fit_transform(xts),
            columns=xts.columns, index=xts.index) #scaling the test set
xts #viewing it after scaling

price  retail_price  currency_buyer  units_sold  uses_ad_boosts  \
0    0.250000      0.023952             0.0    0.000070             1.0   
1    0.315789      0.035928             0.0    0.049971             0.0   
2    0.210526      0.089820             0.0    0.009970             1.0   
3    0.894737      0.155689             0.0    0.049971             1.0   
4    0.578947      0.479042             0.0    0.199976             0.0   
..        ...           ...             ...         ...             ...   
474  0.789474      0.077844             0.0    0.000970             1.0   
475  0.263158      0.095808             0.0    0.049971             1.0   
476  0.201579      0.299401             0.0    0.000470             1.0   
477  0.105263      0.011976             0.0    0.000970             1.0   
478  0.631579      0.059880             0.0    0.000970             1.0   

     badges_count  badge_local_product  badge_product_quality  \
0             0.0                  0.0                    0.0   
1             0.0                  0.0                    0.0   
2             0.0                  0.0                    0.0   
3             0.0                  0.0                    0.0   
4             0.0                  0.0                    0.0   
..            ...                  ...                    ...   
474           0.0                  0.0                    0.0   
475           0.0                  0.0                    0.0   
476           0.0                  0.0                    0.0   
477           0.0                  0.0                    0.0   
478           0.0                  0.0                    0.0   

     badge_fast_shipping      tags  ...  inventory_total  origin_country  \
0                    0.0  0.057906  ...              1.0            0.25   
1                    0.0  0.674833  ...              1.0            0.25   
2                    0.0  0.881960  ...              1.0            0.25   
3                    0.0  0.893096  ...              1.0            0.25   
4                    0.0  0.146993  ...              1.0            0.25   
..                   ...       ...  ...              ...             ...   
474                  0.0  0.895323  ...              1.0            0.75   
475                  0.0  0.812918  ...              1.0            0.25   
476                  0.0  0.795100  ...              1.0            0.75   
477                  0.0  0.614699  ...              1.0            0.25   
478                  0.0  0.271715  ...              1.0            0.25   

     merchant_title  merchant_info_subtitle  merchant_rating_count  \
0          0.629723                0.190931               0.000004   
1          0.808564                0.622912               0.005016   
2          0.287154                0.491647               0.012503   
3          0.720403                0.594272               0.018878   
4          0.471033                0.749403               0.180875   
..              ...                     ...                    ...   
474        0.120907                0.195704               0.000681   
475        0.103275                0.711217               0.060561   
476        0.773300                0.553699               0.000068   
477        0.634761                0.653938               0.001293   
478        0.768262                0.649165               0.053759   

     merchant_rating  merchant_id  merchant_profile_picture  theme  \
0           0.000000     0.957179                   1.00000    0.0   
1           0.646897     0.410579                   1.00000    0.0   
2           0.635963     0.236776                   1.00000    0.0   
3           0.644844     0.642317                   1.00000    0.0   
4           0.672970     0.017632                   1.00000    0.0   
..               ...          ...                       ...    ...   
474         0.387675     0.904282                   1.00000    0.0   
475         

In [51]:
#Now the svm model
from sklearn.svm import SVC
model = SVC() #creating the svm model
model.fit(xtr_train, ytr_train) #fitting the model
y_pred = model.predict(xtr_valid) 
y_pred #showing my predictions before tuning

array([4., 4., 4., 5., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 5., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 5.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [48]:
#tuning the parameters using GridSearchCV
from sklearn.model_selection import GridSearchCV

# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],'gamma': [1, 0.1, 0.01, 0.001, 0.0001],'kernel': ['rbf']}

grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)

# fitting the model for grid search
grid.fit(xtr_train, ytr_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.714 total time=   0.1s


C:\Users\mylap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.714 total time=   0.1s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.709 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.709 total time=   0.1s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.709 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.709 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.709 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.709 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.714 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.714 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.709 total time=   0.0s
[CV 4/5] END .....C=0.1, gam

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [49]:
# print best parameter after tuning
print(grid.best_params_)
 
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

{'C': 1000, 'gamma': 0.01, 'kernel': 'rbf'}
SVC(C=1000, gamma=0.01)


In [52]:
#Validation after tuning
y_pred = grid.predict(xtr_valid)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(ytr_valid, y_pred))
print(classification_report(ytr_valid, y_pred))

[[  1   0   0   0   0   0]
 [  0   0   0   3   0   0]
 [  0   0   1  31   0   0]
 [  0   1   0 149   2   0]
 [  0   0   0  26   4   0]
 [  0   0   0   0   1   0]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00         1
         2.0       0.00      0.00      0.00         3
         3.0       1.00      0.03      0.06        32
         4.0       0.71      0.98      0.83       152
         5.0       0.57      0.13      0.22        30
         6.0       0.00      0.00      0.00         1

    accuracy                           0.71       219
   macro avg       0.55      0.36      0.35       219
weighted avg       0.72      0.71      0.62       219



C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [53]:
from sklearn.metrics import f1_score
f1_score(ytr_valid, y_pred, average='micro') 

0.7077625570776257

In [54]:
# concatenating x_test and id_test along columns in order to be able to call products with its ids when testing
final_test = pd.concat([xts,idts], axis=1)
final_test.set_index("id", inplace = True)

In [55]:
_id = final_test.index
pred_test = grid.predict(final_test)

pred_df = pd.DataFrame(data={'id': np.asarray(_id), 'rating': pred_test})

pred_df.to_csv('pred_walkthrough.csv', index=False) #generating the submission file

In [56]:
##after submitting the pred_walkthrough file on kaggle , it gave me an accuracy of 0.75732
#unfortunately my accuracy dropped
#I will try changing a bit in the way I tuned my parameters


In [57]:
#Support Vector Machine
classifier_df = SVC(kernel = 'linear' , random_state = 0)
classifier_df.fit(xtr_train, ytr_train)
#predicting test data result
y_pred = classifier_df.predict(xtr_valid) 
y_pred #showing my predictions before tunin

array([4., 4., 4., 5., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 4., 5., 4.,
       4., 5., 4., 4., 4., 4., 5., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5.,
       4., 4., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 3., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 5.,
       4., 4., 4., 4., 4., 5., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 3., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 5., 5., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 4., 4., 4.])

In [58]:
#applying Gridsearchcv to find the best model
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [1,10,100], 'kernel': ['linear']}]
grid_search = GridSearchCV(estimator= classifier_df,
                          param_grid = parameters, scoring = 'accuracy',cv = 10)
grid_search = grid_search.fit(xtr_train, ytr_train) #fitting with the new parameters

C:\Users\mylap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


In [59]:
#Validation after tuning
y_pred = grid_search.predict(xtr_valid)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(ytr_valid, y_pred))
print(classification_report(ytr_valid, y_pred))

[[  0   0   0   1   0   0]
 [  0   0   0   3   0   0]
 [  0   0   0  32   0   0]
 [  0   0   1 144   7   0]
 [  0   0   0  23   7   0]
 [  0   0   1   0   0   0]]
              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00         1
         2.0       0.00      0.00      0.00         3
         3.0       0.00      0.00      0.00        32
         4.0       0.71      0.95      0.81       152
         5.0       0.50      0.23      0.32        30
         6.0       0.00      0.00      0.00         1

    accuracy                           0.69       219
   macro avg       0.20      0.20      0.19       219
weighted avg       0.56      0.69      0.61       219



C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [60]:
from sklearn.metrics import f1_score
f1_score(ytr_valid, y_pred, average='micro') 

0.6894977168949772

In [61]:
_id = final_test.index
pred_test = grid_search.predict(final_test)

pred_df = pd.DataFrame(data={'id': np.asarray(_id), 'rating': pred_test})

pred_df.to_csv('pred_walkthrough.csv', index=False) #generating the submission file

In [62]:
# on kaggle, the accuracy remained the same : 0.75732
#I now want to try the naive bayes model

In [64]:
#naive bayes
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB() #creating the gaussian naive bayes model
nb_classifier.fit(xtr_train, ytr_train) #fitting it to my data
y_pred = nb_classifier.predict(xtr_valid) #testing before tuning
y_pred#showing predictions

array([5., 2., 3., 5., 2., 3., 2., 2., 3., 3., 5., 3., 2., 5., 3., 5., 2.,
       3., 5., 5., 2., 2., 2., 4., 3., 3., 3., 3., 2., 2., 3., 2., 2., 3.,
       2., 2., 3., 3., 4., 3., 3., 3., 3., 4., 2., 2., 3., 4., 3., 2., 4.,
       3., 2., 3., 2., 3., 2., 3., 3., 2., 2., 2., 5., 3., 3., 3., 2., 3.,
       2., 3., 4., 4., 2., 2., 3., 2., 3., 3., 2., 2., 2., 2., 3., 2., 5.,
       4., 3., 2., 2., 2., 3., 3., 2., 5., 3., 3., 3., 2., 3., 3., 2., 2.,
       2., 4., 2., 2., 2., 3., 2., 3., 2., 3., 2., 3., 3., 3., 2., 3., 3.,
       3., 5., 5., 3., 2., 3., 2., 5., 2., 2., 2., 3., 5., 3., 2., 3., 5.,
       3., 3., 2., 3., 3., 5., 3., 2., 3., 3., 3., 2., 5., 2., 4., 3., 3.,
       3., 3., 2., 2., 2., 2., 3., 3., 2., 3., 5., 3., 2., 2., 4., 3., 3.,
       2., 3., 3., 2., 2., 2., 3., 5., 5., 2., 2., 3., 3., 3., 2., 3., 3.,
       3., 3., 3., 3., 4., 5., 2., 3., 2., 3., 3., 5., 3., 2., 3., 3., 2.,
       3., 2., 3., 3., 2., 3., 3., 2., 5., 3., 3., 2., 5., 3., 3.])

In [65]:
#Tuning the hyperparameters
from sklearn.model_selection import GridSearchCV
params_NB = {'var_smoothing': np.logspace(0,-9, num=100)}
gs_NB = GridSearchCV(estimator=nb_classifier, param_grid = params_NB, verbose=1, scoring='accuracy') 
gs_NB.fit(xtr_train, ytr_train)
var_value = gs_NB.best_params_.get('var_smoothing')
gnb = GaussianNB(var_smoothing = var_value)


Fitting 5 folds for each of 100 candidates, totalling 500 fits


C:\Users\mylap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


In [66]:
#Testing GNB
gnb.fit(xtr_train, ytr_train)
y_pred = gnb.predict(xtr_valid)
y_pred

array([4., 4., 4., 5., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 4., 5., 4.,
       4., 5., 4., 4., 4., 1., 5., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5.,
       4., 4., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 5., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 5.,
       4., 4., 4., 4., 4., 5., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5., 4., 1., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 5., 5., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 4., 4., 4.])

In [67]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(ytr_valid, y_pred))
print(classification_report(ytr_valid, y_pred))

[[  1   0   0   0   0   0]
 [  0   0   0   3   0   0]
 [  0   0   0  32   0   0]
 [  1   0   0 143   8   0]
 [  0   0   0  23   7   0]
 [  0   0   0   0   1   0]]
              precision    recall  f1-score   support

         1.0       0.50      1.00      0.67         1
         2.0       0.00      0.00      0.00         3
         3.0       0.00      0.00      0.00        32
         4.0       0.71      0.94      0.81       152
         5.0       0.44      0.23      0.30        30
         6.0       0.00      0.00      0.00         1

    accuracy                           0.69       219
   macro avg       0.27      0.36      0.30       219
weighted avg       0.56      0.69      0.61       219



C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mylap\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [68]:
from sklearn.metrics import f1_score
f1_score(ytr_valid, y_pred, average='micro') 

0.6894977168949772

In [69]:
_id = final_test.index
pred_test = gnb.predict(final_test)

pred_df = pd.DataFrame(data={'id': np.asarray(_id), 'rating': pred_test})

pred_df.to_csv('pred_walkthrough.csv', index=False) #generating the submission file

In [ ]:
## on kaggle, the accuracy remained the same : 0.75732
